using DataGridExtensions;
using System;
using System.ComponentModel;
using System.Data;
using System.Windows.Controls;

namespace Table2Chart.Views
{
    /// <summary>
    /// ExcelReaderView.xaml 的交互逻辑
    /// </summary>
    public partial class ExcelReaderView : UserControl
    {
        public ExcelReaderView()
        {
            InitializeComponent();
        }

        private void RadioButton_MouseDown(object sender, System.Windows.Input.MouseButtonEventArgs e)
        {
            if (e.RightButton == System.Windows.Input.MouseButtonState.Pressed)
                e.Handled = true;
        }

        private int index = 0;

        private void DataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            // Use the integer filter for the integer column.
            bool currentFilterCanVisible = true;
            var dataGrid = (DataGrid)sender;
            if (e.Column is DataGridTextColumn &&
                dataGrid.ItemsSource is ICollectionView collectionView &&
                collectionView.SourceCollection is DataView dataView &&
                dataView?.Table?.Rows?.Count > 0)
            {
                var currentData = dataView.Table.Rows[0].ItemArray[index].ToString();
                if (DateTime.TryParse(currentData, out _))
                {
                    currentFilterCanVisible = false;
                }
                if (!double.TryParse(currentData, out _))
                {
                    currentFilterCanVisible = false;
                }
            }
            if (e.PropertyType == typeof(DateTime))
            {
                currentFilterCanVisible = false;
            }
            e.Column.SetIsFilterVisible(currentFilterCanVisible);
            index++;//由于是按顺序加载的
        }

        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            index = 0;//表加载完后清零
        }
    }
}